on:
  push:
    branches:
      - branchHTTPserver  

jobs:
  test:
    runs-on: ubuntu-latest  

    steps:
      - name: Check if Docker image exists
        run: |
          if ! docker image inspect trembachanna/funcaserver > /dev/null 2>&1; then
            echo "Docker image does not exist. Pulling image...";
            docker pull trembachanna/funcaserver;
          else
            echo "Docker image exists. Skipping pull.";
          fi

      - name: Run funcA server container
        run: |
          docker run -d -p 8081:8081 trembachanna/funcaserver
          echo "Server is running..."

      - name: Wait for server to start
        run: |
          echo "Waiting for the server to be ready..."
          sleep 5 

      - name: Run tests on the running server
        run: |
          echo "Running tests..."
          curl http://127.0.0.1:8081/trigvalues
          g++ -o main tests/main.cpp && ./main
