name: Test Server Response Time

on:
  push:
    branches:
      - branchHTTPserver 

jobs:
  test:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - name: Pull Docker Image
        run: docker pull trembachanna/funcaserver
      - name: Run tests inside Docker container
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace trembachanna/funcaserver \
          g++ -o main tests/main.cpp && ./main
