name: Test Server Response Time

on:
  push:
    branches:
      - branchHTTPserver  

jobs:
  test:
    runs-on: ubuntu-latest  

    steps:
      - name: Check if Docker image exists
        run: |
          if ! docker image inspect trembachanna/funcaserver > /dev/null 2>&1; then
            echo "Docker image does not exist. Pulling image...";
            docker pull trembachanna/funcaserver;
          else
            echo "Docker image exists. Skipping pull.";
          fi

      - name: Start funcA server in Docker container
        run: |
          echo "Starting funcA server in Docker container...";
          docker run -d --name funcaserver -p 8081:8081 trembachanna/funcaserver

      - name: Run tests locally in Docker container
        run: |
          echo "Running tests in Docker container...";
          docker run --rm -v $(pwd):/workspace -w /workspace g++ -o main tests/main.cpp && ./main

      - name: Stop funcA server container
        run: |
          echo "Stopping funcA server container...";
          docker stop funcaserver
