name: FuncA Server Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up C++ environment
        uses: actions/setup-cpp@v1
      - name: Install autotools
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake libtool
      - name: Run autoreconf
        run: |
          autoreconf --install
      - name: Run ./configure
        run: |
          ./configure
      - name: Build funcA server
        run: |
          make 
      - name: Run funcA server
        run: |
          ./funcA &  
      - name: Run tests
        run: |
          g++ tests/main.cpp -o tests/main.out
          ./tests/main.out
      - name: Check Docker image trembachanna/funcaserver
        run: |
          docker pull trembachanna/funcaserver
          docker run -d --name funcA-check trembachanna/funcaserver
          docker ps -a
      - name: Stop server and containers
        run: |
          # Завершення роботи сервера funcA
          pkill funcA
          # Зупинка та видалення контейнерів Docker
          docker stop funcA-check
          docker rm funcA-check
