name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    branch: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get install -y automake autoconf g++ make
    - name: Generate configure script
      run: aclocal && automake --add-missing && autoconf
    - name: Run configure script
      run: ./configure
    - name: Build the project
      run: make
