name: Build and Push Docker Image

on:
  push:
    branches:
      - branchHTTPserver
  pull_request:
    branches:
      - branchHTTPserver

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: QEMU install
      uses: docker/setup-qemu-action@v3
    - name: Install Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: build ls
      run: docker buildx ls
    - name: Log in to dockerhub
      run: docker login -u ${{ vars.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
    - name: Build Dockerfile image(amd64)
      run: docker build --platform=linux/amd64 -t trembachanna/funcaserver:amd64 --push .
    - name: Build Dockerfile image(arm64)
      run: docker build --platform=linux/arm64 -t trembachanna/funcaserver:arm64 --push .
    - name: Manifest
      run: docker manifest create trembachanna/funcaserver --amend trembachanna/funcaserver:amd64 --amend trembachanna/funcaserver:arm64
    - name: Push manifest
      run: docker manifest push trembachanna/funcaserver
